version: "3.7"
services:
  pomodomore:
    image: node:16.3-alpine
    container_name: pomodomore-frontend
    hostname: pomodore
    ports:
      - "3000:3000"
      - "9229:9229"
    expose:
      - "3000"
    volumes:
      - /home/sidoku/projects/pomo-do-more-2:/app
    working_dir: /app
    command: "yarn dev --host"
